### ISSUE TITLE
Error in index.php

### ISSUE THREAD

**Issue by juniornunes** [LionsHead/Steam-Web-API#1]
Fatal error: Class 'DotaApi' not found in /home/lasthit/www/SteamApi/index.php on line 10

<?php
$api = new DotaApi(STEAM_KEY);

# Live league games
$json = $api->getLiveLeagueGames();
print_r($json);

# Dota 2 match details info
$match_id = 1745689587; // ti5 final
$json = $api->getMatchDetails($id);
print_r($json);
?>

**Comment by LionsHead** [comment]
use php namespase? 
```php
<?php

use \SteamApi\SteamApi; # steam\etc
use \SteamApi\JsFeed; # hero\items\lore
use \SteamApi\DotaApi; # dota

$api = new DotaApi(STEAM_KEY);

$json = $api->getLiveLeagueGames();
print_r($json);
```

**Comment by juniornunes** [comment]
sorry thanks
